// React
import { useState, useEffect } from "react"
// Next
import Head from "next/head"
// AgGrid
import { AgGridReact } from "ag-grid-react"
// Chart
import Graph from "@/src/components/chart/Graph"
// css AgGrid
import "ag-grid-community/styles/ag-grid.css"
import "ag-grid-community/styles/ag-theme-alpine.css"
// css local
import styles from "@/styles/Home.module.css"

const App = () => {
  const [rowData, setRowData] = useState([])
  const [columnDefs, setColumnDefs] = useState([
    { field: "make", filter: true, width: 150 },
    { field: "model", sortable: true, filter: true, width: 150 },
    { field: "price", sortable: true, minWidth: 150 },
  ])

  const pagination = true
  const paginationPageSize = 10

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        "https://www.ag-grid.com/example-assets/row-data.json"
      )
      const data = await response.json()
      setRowData(data)
    }
    fetchData()
  }, [])
  /** or
  fetch("https://www.ag-grid.com/example-assets/row-data.json")
    .then((result) => result.json())
    .then((rowData) => setRowData(rowData))
 */

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.head_1}>
          React Data Grid: Get Started with AG Grid
        </h1>
        <div className={styles.grid}>
          <div className="ag-theme-alpine" style={{ height: 400, width: 500 }}>
            <h2 className={styles.head_2}>AgGrid Table</h2>
            <AgGridReact
              rowData={rowData}
              columnDefs={columnDefs}
              pagination={pagination}
              paginationPageSize={paginationPageSize}
            />
          </div>
          <div className={styles.box}>
            <Graph />
          </div>
        </div>
      </main>
    </>
  )
}

export default App
